### PR TITLE
Updated HTML_CodeSniffer to 2.1.0

### PR DESCRIPTION
**Pull request by HugoGiraudel**
HTML_CodeSniffer just released 2.1.0. This PR updates the vendor file. :)

### CODE REVIEW

**Comment by rowanmanning** [comment]
Hi @HugoGiraudel, thanks for doing this!

It seems that some new messages are coming through though, which is breaking the integration tests. If you have time to fix them, that'd be great, otherwise I'm happy to when I get a chance. If you'd like some pointers on how the integration tests work then I'm happy to explain that too :)

**Comment by HugoGiraudel** [comment]
Hey Rowan! I’m not sure I will have time today unfortunately. Maybe during the week, but that’s not a given. I’m sorry for not being able to push this PR up to the end. :(

**Comment by rowanmanning** [comment]
That's OK :) I'll take a look ASAP

**Comment by HugoGiraudel** [comment]
Hey there! I was having a look at this again, but I’m not sure how to fix these tests… I could make sure they pass, but I guess that’s not really the point is it? :D

**Comment by rowanmanning** [comment]
Ha :) no not quite the point. I still haven't had a proper chance to look as have been busy with other things. Still my intention to at some point soon though!

**Comment by andrewmee** [comment]
Hey @HugoGiraudel  I've picked up the start you made here and opened a fresh PR (as I can't push to your fork) here; https://github.com/pa11y/pa11y/pull/289

Looks like it was the new behaviour around doctype detection that was meaning our integration test-cases started showing different results!

**Comment by HugoGiraudel** [comment]
Cool!

**Pull request closed without merging**
