### PR TITLE
Upgrade to puppeteer@0.13.0

### PR DESCRIPTION
**Pull request by colinrotherham**
Hi @rowanmanning,

I've completed the upgrade to `puppeteer@0.13.0` from https://github.com/pa11y/pa11y/issues/358.

There were a few breaking API changes despite it being a minor bump, these are all mentioned in the Puppeteer release notes though: https://github.com/GoogleChrome/puppeteer/releases

### CODE REVIEW

**Comment by colinrotherham** [comment]
Looks like someone else made the same pull request after me via https://github.com/pa11y/pa11y/pull/360

The difference? We need to decide which "network idle" event to use:

1. `networkidle0`  
Appears to signal a totally idle network

2. `networkidle2`
A new heuristic: Delays the **page.goto** promise from resolving until there are no more than 2 network requests for at least 500ms

Attempting to use the old `networkidle` event shows a warning to suggest `networkidle2` instead.

This appears to be a better heuristic to cater for sites that are never idle, e.g. making frequent analytics calls in the background.

**Comment by Godoy** [comment]
Sorry, I will close my PR :)

**Comment by colinrotherham** [comment]
@godoy Depends, I'm not sure (yet) if `networkidle0` is preferred over `networkidle2`!

See what @rowanmanning thinks.

**Comment by Godoy** [comment]
@colinrotherham no problem, I had this same doubt. Anyway, I think we can discourse and change your pr if necessary

**Comment by rowanmanning** [comment]
This is looking great, and I think yes `networkidle2` is the way to go. Going to merge and release

**Comment by NguoiThuaKe** [comment]
Tks

**Pull request merged**
