### PR TITLE
[5.x] Fixes for wait-for-url actions and puppeteer's addScriptTag

### PR DESCRIPTION
**Pull request by sillero**
Hi there o/
First of all, thanks for your hard work. I love pa11y and I'm very excited about sidekick :)

I faced some issues while trying the beta, and since I've been doing some stuff with puppeteer I thought I could help you out with these issues:

- When you try to `.waitForFunction` and the pages navigates away, it doesn't work.  
To detect navigation changes, it's best to just use `.waitForNavigation`. 
- To inject a JS file, the current api is `.addScriptTag({ path: "..." })`

I had to rewrite a bunch of tests, so let me know if this needs more fixing.

### CODE REVIEW

**Comment by sillero** [comment]
If anyone could help me figure out how to fix those 2 CLI tests, I'd appreciate it.

**Comment by rowanmanning** [comment]
Ah cool, good spot. Although I'm surprised the tests haven't caught this. I'll have a look as soon as possible, and maybe try to write a failing test just to verify.

Actually do you have an example of a URL and config file which demonstrate this?

**Comment by sillero** [comment]
Full disclosure, I work for Trello/Atlassian

https://trello.com/login
```
{
  "actions": [
    "set field #user to _____",
    "set field #password to ____",
    "click element #login",
    "wait for path to not be /login"
  ]
}
```

**Comment by rowanmanning** [comment]
Hi @sillero, I finally have a chance to look at this, but I'm currently getting timeout errors for all URLs (regardless of config). Could you confirm that this works for you still? Thanks

**Comment by rowanmanning** [comment]
OK I really can't replicate the behaviour you're describing with the `wait for path to not be ...` etc actions 😄 I've tried quite a few sites that redirect after login which work correctly. Is it possible that something changed in a later version of Puppeteer?

Anyway, I'm gonna remove this from the 5.0 milestone so we can cut a stable release. I'll leave open for now so we can discuss if you're still having issues.

**Comment by joeyciechanowicz** [comment]
Can this PR be rebased against `master` now that `Pa11y 5.x` has been merged in?

Regarding the changes themselves, the `addScriptTag` change look great 👍.
I have some concerns with the `. waitForNavigation`, though I may have this wrong. Take the following set of actions:
1. Click a link on the page which navigates to a new page
1. Use a `wait for navigation`  action

Isn't it possible for Puppeteer to have navigated to the new page _before_ the second `wait for` action gets called?

**Comment by joeyciechanowicz** [comment]
Reviewing this PR again, it would make sense to split this PR into two. One for the bugfix. And one for the new feature. 
Then we can review it easier and discuss the pros/cons of the new feature, without it being for multiple purposes.

**Pull request closed without merging**
