### PR TITLE
Add windows and macos to the test matrix

### PR DESCRIPTION
**Pull request by josebolos**

### CODE REVIEW

**Comment by aarongoldenthal** [comment]
@josebolos If you haven't found it already, pa11y does have at least some of the same Windows issues as pa11y-ci, noted in https://github.com/pa11y/pa11y-ci/pull/177 (and at least one other, as seen with the current failure setting an environment variable). If you're looking for help I'm happy to take a look.

**Comment by josebolos** [comment]
Hi @aarongoldenthal! I did see your PR indeed, that's what led me to create this one. :joy: I'm off for Easter now but I'm happy to have a look when I'm back if you don't get round to it. Thanks!

**Comment by aarongoldenthal** [comment]
@josebolos Hope you have a good break. Windows updates are in https://github.com/pa11y/pa11y/pull/644.

**Review by joeyciechanowicz — APPROVED** [review]
Good thinking

**Comment by josebolos** [comment]
Changing the base branch to `next` so we can pile up all the breaking changes for v7 there without messing up master.

**Pull request merged**
