### PR TITLE
Exclude Cookie header from being lowercased

### PR DESCRIPTION
**Pull request by liamkeaton**
The headers keys are being lowercased before being set, it's not clear
why but this is causing the Cookie header to not be set correctly in
puppeteer.

### CODE REVIEW

**Comment by thibaudcolas** [comment]
@liamkeaton could you explain what you mean by "not be set correctly"? This seems to be working fine for me at least.

From what I can see in the Puppeteer docs (https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#requestheaders), it seems like it's expected for header names to be lower-case. It doesn't say why though 😅.

**Comment by liamkeaton** [comment]
@thibaudcolas by not correctly I meant not at all. Before this change I had a session cookie that needed to be set for the page to be accessed. I did find it weird why this hadn't been spotted sooner though if this was the case!

**Comment by thibaudcolas** [comment]
👍 gotcha. This is working fine for me at least (https://github.com/thibaudcolas/wagtail-tooling/blob/8663e51c2a395688e6fefd9e3156d5b5ae92bff8/accessibility/pa11y-test.js#L93-L107), so there might be something else at play here. Let's see what other people think.

**Comment by liamkeaton** [comment]
@thibaudcolas That is very strange, without this fix it fails and with it passes. There is also an [issue](https://github.com/pa11y/pa11y/issues/441) that seems to be similar to what i'm experiencing.

**Comment by liamkeaton** [comment]
I put together a [minimal use case](https://github.com/liamkeaton/pa11y-cookie) to get to the bottom of this and I disproved my theory. The cookie is getting parsed correctly whether upper or lower cased when using pa11y directly.

**Comment by liamkeaton** [comment]
I've found this is a concurrency issue with Pa11y-CI, will issue a PR over there to correct it.

**Pull request closed without merging**
