### PR TITLE
Wait for element to be action

### PR DESCRIPTION
**Pull request by iandevlin**
As discussed, this is a work in progress PR for adding a `wait-for` action.

### CODE REVIEW

**Comment by rowanmanning** [comment]
Hey @iandevlin, this is looking great so far. Apologies for the delay in my response, but been busy :)

In terms of getting the build passing, I think the ideal first step will be to conform to the linter (you can run `make lint`). Then we can talk more about the actual tests.

Next up integration tests will be an ideal first set of tests to complete rather than unit tests. If it helps then I'm happy to write some integration tests which outline how I'd expect this feature to work, then we could adapt them from there?

Lastly the unit tests for this will probably be quite complex. That's fine and I'm happy to work on them with you. There may be places we can split out code and simplify the tests.

**Comment by iandevlin** [comment]
Oops, sorry about the lint errors, I have now fixed them.
Yes, it would be helpful if you could start with some integration tests, that would be useful for me. Thanks!

**Comment by iandevlin** [comment]
@rowanmanning Hello! I was just wondering if you have an update on this? I appreciate - of course - that this is being done in your spare time, but I would like to see this move forward so an update would be appreciated. I would like to help, but I really need help with the rests.
Thanks!

**Comment by rowanmanning** [comment]
Hi @iandevlin, I'm on it, I've written a lot of the integration tests but keep getting sidelined :)

I was going to suggest that maybe we split this into separate actions for element added/removed, and element visible/hidden. I know it means some duplication but will simplify testing quite a lot based on what I've looked at so far. Have any thoughts on this?

**Comment by iandevlin** [comment]
Hey! Cool no worries, I was just wondering, thanks for the update.

I don't mind to be honest, if you think that it would make things easier and don't mind the duplication, then I can split it.

**Comment by seando** [comment]
Is this feature going to be merged any time soon? It's an excellent one.

**Comment by iandevlin** [comment]
@rowanmanning Due to some excellent work by my colleagues @frvge and @anilanar, there are now tests available.

**Comment by rowanmanning** [comment]
This is great! Thanks @iandevlin. I'd like to get this merged in asap so will attempt to this week – I've been pretty busy and a lot of my OSS time has been dedicated to headless chrome :)

**Comment by rowanmanning** [comment]
I'm gonna have to open this as a separate PR that I can edit to resolve the conflicts. See #290

**Comment by iandevlin** [comment]
@rowanmanning Cool, looking forward to seeing it merged!
And the move to headless Chome looks good so yay for that too :-)

**Pull request closed without merging**
