### PR TITLE
updates pa11y-axe-runner to 1.0.2

### PR DESCRIPTION
**Pull request by joeyciechanowicz**
Gives us lovely output like the following!

image

### CODE REVIEW

**Comment by angelblade27** [comment]
@joeyciechanowicz how did you get the report to show the rule like that? I verified I'm on pa11y-axe-runner 1.0.2 
`➜  ngrok npm list -g --depth=1| grep pa11y
├─┬ pa11y@5.3.0
│ ├── pa11y-reporter-cli@1.0.1
│ ├── pa11y-reporter-csv@1.0.0
│ ├── pa11y-reporter-json@1.0.0
│ ├── pa11y-runner-axe@1.0.2
│ ├── pa11y-runner-htmlcs@1.2.0
├─┬ pa11y-reporter-html@2.0.0`

Yet my report looks like this still
Screen Shot 2020-08-04 at 10 26 10 AM

**Comment by joeyciechanowicz** [comment]
Which part do you mean - the highlighting, or the aXe rules?

If it's highlighting then thats because I had an active search in my terminal. Running axe requires you run `pa11y` with `--runners axe`

**Comment by angelblade27** [comment]
@joeyciechanowicz thanks for the response. It was the axe rules.

eg when I run it against amazon I don't see the WGAG rule being printed out
```
➜  ~ pa11y --runner axe amazon.com

Welcome to Pa11y

 > Running Pa11y on URL http://amazon.com

Results for URL: https://www.amazon.com/

 • Error: ARIA hidden element must not contain focusable elements (https://dequeuniversity.com/rules/axe/3.5/aria-hidden-focus?application=axeAPI)
   ├── aria-hidden-focus
   ├── #ape_Gateway_right-2_desktop_placement
   └── <div id="ape_Gateway_right-2_desktop_placement" class="copilot-secure-display celwidget text/x-dacx-safeframe" cel_widget_id="adplacements:Gateway:right-2:desktop" data-campaign="7716" style="width: 300px; overflow:hidden;" data-ad-details="{&quot;s...

 • Error: ARIA hidden element must not contain focusable elements (https://dequeuniversity.com/rules/axe/3.5/aria-hidden-focus?application=axeAPI)
   ├── aria-hidden-focus
   ├── #ape_Gateway_desktop-ad-center-1_desktop_placement
   └── <div id="ape_Gateway_desktop-ad-center-1_desktop_placement" class="copilot-secure-display celwidget text/x-dacx-safeframe" cel_widget_id="adplacements:Gateway:desktop-ad-center-1:desktop" data-campaign="6629" style="max-width: 970px; min-width: 970p...

 • Error: ARIA hidden element must not contain focusable elements (https://dequeuniversity.com/rules/axe/3.5/aria-hidden-focus?application=axeAPI)
   ├── aria-hidden-focus
   ├── #ape_Gateway_right-7_desktop_placement
   └── <div id="ape_Gateway_right-7_desktop_placement" class="copilot-secure-display celwidget text/x-dacx-safeframe" cel_widget_id="adplacements:Gateway:right-7:desktop" data-campaign="7717" style="width: 300px; overflow: hidden;" data-ad-details="{&quot;...
```

You mentioned ```--runners``` with the extra s. i don't see that in the help doc which would I believe means it would default to running htmlcs. For that runner I do the see the WCGAG rules getting printed out

**Comment by angelblade27** [comment]
@joeyciechanowicz Just curious if you saw what my mistake might be?

**Pull request merged**
