### PR TITLE
Merge pa11y ci

### PR DESCRIPTION
**Pull request by joeyciechanowicz**
First PR of the merge!

I've brought the entire commit history from `pa11y-ci` so it's not lost, meaning this is a painful PR to review. All the changes I've made are contained in a single commit which can be reviewed in isolation here: https://github.com/pa11y/pa11y/pull/609/commits/d08dbd6f529e90639b138c75ffe0da8f0bfb98e3

This PR is just to get the `pa11y-ci` code working within `pa11y` and does not address the actual functional changes we need to merge `pa11y-ci`.

### CODE REVIEW

**Comment by j-mendez** [comment]
I think it makes sense to remove the CLI usage on this repo and have the CLI handle that. I have a fork here https://github.com/j-mendez/litepa11y/tree/main/lib doing so and its a drastic smaller bundle size and more appropriate for using in a API and portability. The fork also changes a bit of things to crank out some performance. @josebolos @joeyciechanowicz

**Comment by danyalaytekin** [comment]
Hi @joeyciechanowicz, thank you for this PR.  We're currently considering the approach we'd like to take for this assimilation and I'll close the PR for now.  But I'll definitely be keeping this PR bookmarked.  Some of the patterns of where things are similar and where they differ that you've spotted are very informative.

@smustgrave Yes, sitemaps are part of the specification.  In short, we don't want to lose any functionality.

@j-mendez I tried to take a look at [litepa11y](https://github.com/j-mendez/litepa11y) but, alas, I think we're too late.  We'll bear the suggestion in mind, although it may turn out to run counter to our other motivations here.

Thanks everyone.  ❤️

**Comment by j-mendez** [comment]
@danyalaytekin the project is now called [kayle](https://github.com/a11ywatch/kayle). We made huge rewrites on htmlcs, and axe with tons of bug fixes and performance improvements. We also made the runner gathering of issues performant with custom algorithms to build the data and moved locales to split scripts for performance. Now we are working on the first Rust/Wasm web accessibility engine as the next steps. A lot of the foundation is there so having nanosecond audits to 1ms should be coming in a couple months while maintaining accuracy and more issues available to be handled since the tree alg that we have opens up new doors.

**Comment by danyalaytekin** [comment]
Thanks @j-mendez, sounds impressive!  [A11yWatch](https://a11ywatch.com/blog) is now in my RSS reader.

**Pull request closed without merging**
